name = "macedonian-vibe-news"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "web/.next"

[env.production.vars]
ENVIRONMENT = "production"
NEXT_PUBLIC_SUPABASE_URL = "https://supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "123"

[env.preview.vars]
ENVIRONMENT = "preview"



